language: c
compiler:
  - gcc
#  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libcunit1-dev libcppunit-dev libncurses5-dev
install:
  - cp linux/config-TRAVIS linux/.config
env:
  #- FLAGS=
script:
  - ./compile-kernel
  - ./install-kernel
  - ./compile-user
  - ./install-user-from-scratch
notifications:
  email:
    - ci@bisdn.de
