language: c
compiler:
  - gcc
#  - clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get -qq install gcc-4.7; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 90; export CC="gcc-4.7"
  - sudo apt-get -qq install g++-4.7; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 90; export CXX="g++-4.7"
  - sudo apt-get install -y -qq libcunit1-dev libcppunit-dev libncurses5-dev bc libnl-3-dev
install:
  - cp linux/config-TRAVIS linux/.config
env:
  #- FLAGS=
script:
  - sudo ./compile-kernel
  - sudo ./install-kernel
  - sudo ./install-user-from-scratch
notifications:
  email:
    - ci@bisdn.de
