git:
  depth: 1000
language: c
compiler:
  - gcc
before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ vivid main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libnl-genl-3-dev libnl-3-dev libtool autoconf2.13 git libpcre3 pkg-config libpcre3-dev libprotobuf-dev protobuf-compiler tcpdump libcunit1-dev libcppunit-dev libncurses5-dev bc 1> /dev/null
  - sudo apt-get remove gcc-4.6 1> /dev/null
install:
  - cp linux/config-TRAVIS linux/.config
env:
  #None
script:
  #Set necessary envs (here, not in env!)
  - export PATH_REPO=`pwd`
  - export V=1
  - export PREFIX=/usr/local/irati
  #Kernel
  - cd linux
  - sudo make -j 5 bzImage modules
  - sudo make -j 5 modules_install
  - sudo make install
  - sudo make headers_install
  - cd ..
  #librina
  - cd librina/
  - mkdir -p build
  - sh bootstrap
  - cd build
  - ../configure --disable-silent-rules --with-sysheaders=$PATH_REPO/linux/usr/include --prefix=$PREFIX
  - sudo make -j 5 install
  - sudo make -j 5 check
  - cd ../../
  #rinad
  - cd rinad
  - mkdir -p build
  - sh bootstrap
  - cd build
  - PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig/" ../configure --disable-silent-rules
  - sudo make -j 5 install
  - sudo make -j 5 check
notifications:
  email:
    - irati-ci@freelists.org
